## About This Notebook

In the previous notebook we learned what variables are and how these can store various values (strings, integers ...). 

- In this notebook, we will expand our toolset with a more complex type of variable - **list**. As you will see, a list can store many elements (not just one like a variables in the previous lecture). 
- We will learn later on how to manipulate these lists, such as how to navigate through them and how to retrieve elements from them. 
- In the final part of the notebook we will hop on to a different concept - **loops**. These are closely connected to the topic of lists (and for example retrieval from lists). If the list is *very* long it might become unfeasible to retrieve elements from it manually. We will need loops for this.

Please note that in this notebook you will see **libraries being imported**. To understand what these imports of libraries are (with all the functions and commands) is not yet required knowledge. Try to follow only the examples which are shown.
***

## 1. Lists

From last chapter we have worked with the table below:


| Track_name |  Price |  Currency |  Rating_count_total | User_rating|
|------------|:------:|----------:|---------------------:|-----------:|
| Facebook | 0.0 | USD | 2974676 | 3.5|
| Instagram |    0.0  |   USD |2161558 |4.5|
| Clash of Clans | 0.0|    USD | 2130805 |4.5|
| Temple Run |    0.0  |   USD |1724546 |4.5|
| Pandora - Music & Radio | 0.0|    USD | 1126879 |4.5|

Data Source:  [Mobile App Store Data Set (Ramanathan Perumal)](https://www.kaggle.com/ramamet4/app-store-apple-data-set-10k-apps)</p>

There are 5 rows and 5 columns in this table. Each value in this table is called a **data point**. For example in the first row, we have five data points and they are:

- Facebook
- 0.0
- USA
- 2974676
- 3.5

When we have a collection of data points it is called a **data set**. We can understand the table above as a collection of data points, so we can call the entire table a data set as well. We see that the data set has five rows and five columns. 

When we want to work with data sets in the computer, we need to store them properly in the computer memory so we can retrieve and manipulate the data points according to our needs. To store each data point in the computer, we can for instance take what we have learned so far and do it this way:

In [ ]:
track_name_row1 = 'Facebook'
price_row1 = 0.0
currrency_row1 = 'USD'
rating_count_total_row1 = 2974676
user_rating_row1 = 3.5

**To enter each data point manually in the data set like we did above would involve a lot of labor and is nearly impossible for a big data set. Fortunately, we can store data in another more efficient way by using lists.** See example below:

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
print(row_one)
type(row_one)

How did we create the list above? 

1. Enter a sequence of data points that we want to include in our data set and **separated each with a comma**: 'Facebook', 0.0, 'USD', 2974676, 3.5
2. Use **brackets for surrounding** the sequence of data points

After we created the list, the list is stored in the computer's memory by assignment to the variable name row_one. 

### Task 1.3.1
1. Store the second row as a list in a variable named `row_two`.
2. Store the third row as a list in a variable named `row_three`.
3. Print out `row_two` and `row_three`.

| Track_name |  Price |  Currency |  Rating_count_total | User_rating|
|------------|:------:|----------:|---------------------:|-----------:|
| Facebook | 0.0 | USD | 2974676 | 3.5|
| Instagram |    0.0  |   USD |2161558 |4.5|
| Clash of Clans | 0.0|    USD | 2130805 |4.5|
| Temple Run |    0.0  |   USD |1724546 |4.5|
| Pandora - Music & Radio | 0.0|    USD | 1126879 |4.5|

In [ ]:
# Start your code below:
row_two = ["Instagram", 0.0, "USD", 2161558, 4.5]
print(row_two)
row_three = ["Clash of Clans", 0.0, "USD", 2130805, 4.5]
print(row_three)	 


['Instagram', 0.0, 'USD', 2161558, 4.5]
['Clash of Clans', 0.0, 'USD', 2130805, 4.5]


A list can contain both -- mixed and identical data types.

For example, a list that contains only integers looks like this: `[ 1, 2, 3]`. A mixed data type list looks like the one we created above: `['Facebbok', 0.0, 'USD', 2974676, 3.5]`. In this list, we have:
- Two strings ('Facebook', 'USD')
- Two floats (0.0, 3.5)
- One integer (2974676)

In order to find out the **length of a list, we can use the `len()` command**. 
The row_one list for example has five data points.

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
print(len(row_one))

list_a = [1,2,3]
print(len(list_a))

list_b = []
print(len(list_b))

5
3
0


## 2. Indexing a List

**Each data point or element in the list has a specific index number (position) associated with it**. In Python, the indexing always starts with 0. For example, the first element always has the index number 0, and the second element always has the index number 1, and so on.

To find the index of an element in the list, simply count the position of the index and then minus one. For example, the user rating is the 5th element in the list and it has an index number of 4 (5 - 1 = 4).

*Note: Please really write this down - the indexing in Python starts at 0.*

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
print(row_one[2])

USD


The index number can help us retrieve individual elements from a list. So how do we retrieve the first element? We can enter the list name and then wrap the index number in a bracket. The general formula follows the model:  `list_name[index_number]`. To retrieve each element from the list is useful when we want to perform operations between the elements. For example, we can find out the average and difference between Facebook's and Instagram's ratings by doing this: 

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_two = ['Instagram',0.0, 'USD', 2161558, 4.5]

difference_in_rating = row_two[4] - row_one[4]
average_rating = (row_one[4] + row_two[4])/2

print(difference_in_rating)
print(average_rating)

1.0
4.0


### Task 1.3.2

In the code editor below, you can see the lists for the first three rows from the table. Retrieve the fourth element from each list, which represents the rating each app has received, and fnid the average value of the retrieved numbers.

1. Assign the fourth element from the list ``row_one`` to a variable named ``rating_one``. Don't forget that the indexing starts at 0. <br>
2. Repeat the same step for the fourth element from the list ``row_two``, to a variable named ``rating_two``.<br>
3. Repeat the same step for for the fourth element from the list ``row_three``, to a variable named  ``rating_three``.<br>
4. Add the three numbers from above steps together and save the value to a variable named ``total_rating``.
5. Divide the ``total_rating`` by 3 to get the average number of ratings for the first three rows. Assign the final result to a variable named ``average_rating``.
6. Print `average_rating`.

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_two = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_three = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]

# Start your code below:
rating_one = row_one[3]
rating_two = row_two[3]
rating_three = row_three[3]
total_rating = rating_one + rating_two + rating_three
average_rating = total_rating/3
print(average_rating)

2422346.3333333335


## 3. Negative Indexing

There are two indexing systems for lists in Python.
- Positive indexing: the one we have encountered so far starting with the first element having the index number 0 and the second element having the index number 1, and so on.
- Negative indexing: starting with the **last element** having the index number -1, the second to last element having the index number -2, and so on.

Positive indexing is often put into practice in day to day programming. However, negative indexing can also come in handy when we want to select the last element of a list, especially when this list is long and we have no idea how many elements it contains.

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]

print(row_one[-1])
print(row_one[4])

3.5
3.5


See that the code above, indexing number -1 and 4 retrieve the same result. 
Pay attention: if we try to use an index number that is outside the range of the two indexing systems that are mentioned above, we'll get the following error:

In [ ]:
print(row_one[5])

IndexError: ignored

### Task 1.3.3

The last element in each list represents the rating of each app.

1. Retrieve the ratings for the first three rows (like what you have done in task 2), and then find the average of all the ratings retrieved and print it to the screen.

<b>Try to use the negative indexing system.</b>

In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]

##Your task starts here:
rating_1 = row_1[-2]
rating_2 = row_2[-2]
rating_3 = row_3[-2]
total_rating = rating_1 + rating_2 + rating_3
average_rating = total_rating/3
print(average_rating)


2422346.3333333335


## 4. Retrieving Multiple List Elements
There are occasions where we are asked to retrieve more than just one element from a list. 
Take the list we have already worked with before: `['Facebook', 0.0, 'USD', 2974676, 3.5]`. We're  interested in knowing only the name of the app and the data about ratings (the number of ratings and the rating). Taking what we have learned so far, we can do this as follows:

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
app_name = row_one[0]
rating_count_total = row_one[3]
rating = row_one[-1] # or rating = row_one[4] 

It will be very inefficient if we try to do this for every app in the data table and make our code unnecessarily lengthy and hard to keep track of. 
Alternatively we can store all the data we want to keep track of in a separate list like this:

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]

fb_rating = [row_one[0], row_one[3], row_one[-1]]
print(fb_rating)

['Facebook', 2974676, 3.5]


In the code above we have successfully abstracted all the information we needed from the list into a separate list.

### Task 1.3.4

1. Abstract the rating data for Facebook, Instagram, Pandora - Music & Radio into separate lists. Each list should contain information like: the name of the app, the total rating count, and the user rating. Don't forget the positive index system begins with indexing number 0.
  - For Facebook, assign the list to a variable called `fb_rating_data`
  - For Instagram, assign the list to a variable called `insta_rating_data`
  - For Pandora - Music & Radio, assign the list to a variable called `pan_rating_data`


2. Compute the average user rating for Instagram, and Pandora — Music & Radio using the data you just created ``fb_rating_data``, ``insta_rating_data``, and ``pan_rating_data``.
  - Sum up all the ratings together and compute the average rating.
  - Assign the result to a variable named `avg_rating`.

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_two = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_three = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_four = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_five = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]

# Start your code below:

# Question 1:
fb_rating_data = [row_one[0], row_one[-2], row_one[-1]]
insta_rating_data = [row_two[0], row_two[-2], row_two[-1]]
pan_rating_data = [row_five[0], row_five[-2], row_five[-1]]
print(fb_rating_data)
print(insta_rating_data)
print(pan_rating_data)
# Question 2:
avg_rating = (fb_rating_data[-1] + insta_rating_data[-1] + pan_rating_data[-1]) / 3
print(avg_rating)

['Facebook', 2974676, 3.5]
['Instagram', 2161558, 4.5]
['Pandora - Music & Radio', 1126879, 4.0]
4.0


## 5. List Slicing (IMPORTANT)

In the previous exercise, we retrieved the first, fourth, and the last element and put them into a separate list.
We can also retrieve the first three elements from the list and create a separate pricing data list.

For example:

In [ ]:
row_three = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]

clash_pricing_data = [row_three[0], row_three[1], row_three[2]]
print(clash_pricing_data)

['Clash of Clans', 0.0, 'USD']


However, there is a shortcut in selecting the first three elements like this:

In [ ]:
row_three = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]

clash_pricing_data = row_three[0:3] #This is also known as the syntax shortcut
print(clash_pricing_data)

['Clash of Clans', 0.0, 'USD']


As shown in the code, if we want to select the first <b> n</b> elements from a list called list_one, we can use the syntax shortcut `list_one[0:n]`. 
In the example above, we have selected the first three elements from the list called `row_three`, so we have used: `row_3[0:3]` .
The process of selecting a particular part of a list is known as list slicing.

In order to retrieve any list slice we want, we need to:
1. Identify the first and last element of the slice.
2. Identify the index numbers of the first and last element of the slice.
3. We can then retrieve the list slice we want by using the syntax we just mentioned above like: `list_one[m:n]`, where:
    - m is the index number of the first element of the slice
    - n is the index number of the last element of the slice <b> plus one </b>. (That means if the last element has the index number 5, then <b>n</b> will be 6, and if the last element has the index number 10, then<b> n</b> will be 11, and so on)

There is an even simpler syntax shortcuts when we want to select the first or last n elements (n stands for an integer):
- `list_one[:n]`: when we want to select the first n elements
- `list_one[-n:]`: when we want to select the last n elements

In [ ]:
row_three = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]

first_3 = row_three[:3] #select the first 3 elements
last_3 = row_three[-3:] #select the last 3 elements

print(first_3)
print(last_3)

['Clash of Clans', 0.0, 'USD']
['USD', 2130805, 4.5]


### Task 1.3.5

1. Select the first four elements from `row_one` using the list slicing syntax shortcut and assign the result to a variable named `first_four_elem_fb`.
2. Select the last two elements from `row_one` using the list slicing syntax shortcut and assign the result to a variable named `last_two_elem_fb`.
3. For `row_five`, select the list slice `[ 0.0, 'USD', 1126879]` using the list slicing syntax shortcut and assign the result to a variable named `pan_2_3_4`.

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_two = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_three = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_four = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_five = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]


# Start your code below:
first_four_elem_fb = row_one[0:4]
last_two_elem_fb = row_one[-2:]
pan_2_3_4 = row_five[-4:-1]
print(first_four_elem_fb)
print(last_two_elem_fb)
print(pan_2_3_4)



['Facebook', 0.0, 'USD', 2974676]
[2974676, 3.5]
[0.0, 'USD', 1126879]


## 6. List of Lists
So far we have only worked with a data set of small scale (only five rows!) and we have stored each row as a list in a seprate variable like `row_one`, `row_two`, `row_three`, `row_four`, `row_five`. However, if we had a data set with more than 10,000 rows, then we'd have ended up with 10,000 more variables which is unrealistic and redundant.

To solve this problem, we can store all five lists in one single variable like this:

In [ ]:
row_one = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_two = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_three = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_four = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_five = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]

data_set = [row_one, row_two, row_three, row_four, row_five]
data_set

[['Facebook', 0.0, 'USD', 2974676, 3.5],
 ['Instagram', 0.0, 'USD', 2161558, 4.5],
 ['Clash of Clans', 0.0, 'USD', 2130805, 4.5],
 ['Temple Run', 0.0, 'USD', 1724546, 4.5],
 ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]]

We can see that now the variable data_set contains all five lists `row_one, row_two, row_three, row_four, row_five`. Such a list that contains other lists is called a <b> list of lists </b>.

`data_set` is declared as a list, so we can retrieve the individual list elements and perform list slicing with what we have learned.

In [ ]:
data_set = [row_one, row_two, row_three, row_four, row_five]

#To retrieve the first element
print(data_set[0])

#To retrieve the last element
print(data_set[-1])

#To retrieve the first two list elements 
print(data_set[:2])

['Facebook', 0.0, 'USD', 2974676, 3.5]
['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]
[['Facebook', 0.0, 'USD', 2974676, 3.5], ['Instagram', 0.0, 'USD', 2161558, 4.5]]


There are also cases where we need to retrieve individual elements from a list that's part of a list of lists — for instance, we may want to retrieve the value 'Facebook' from ['Facebook', 0.0, 'USD', 2974676, 3.5], which is now part of the `data_set` list of lists.

In [ ]:
data_set = [row_one, row_two, row_three, row_four, row_five]

#We can retrieve row_one and assign it to a variable like this:
fb_list = data_set[0]

#To print out the facebook list data
print(fb_list)

#To retrieve the first element from fb_list
app_name = fb_list[0]

#Print the result of app_name
print(app_name)

['Facebook', 0.0, 'USD', 2974676, 3.5]
Facebook


In the code above, we have retrieved the first element in two steps: we first retrieved `data_set[0]`, and then we retrieved `fb_row[0]`.
There is a much simpler way to retrieve the value 'Facebook' by chaining the two indices ([0] and [0])
For example `data_set[0][0]` will give you the same output.

In [ ]:
data_set = [row_one, row_two, row_three, row_four, row_five]

print(data_set[0] [3])
#Acessar um elemento de uma lista de um data set 

2974676


### Task 1.3.6


1. In the code editor below please group together the five lists into a **list of lists** named ``app_data_set``.
2. Compute the average rating of the apps by retrieving the right data points from the ``app_data_set`` list of lists.
  - The user rating is always the last element of each row. Sum up the ratings and then divide by the number of ratings to get the average.
  - Assign the result to a variable named ``average_rating``.
  - Print `average_rating`.


In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_4 = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_5 = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]


# Start your code below:
app_data_set = [row_1, row_2, row_3, row_4, row_5]
average_rating = (row_1[-1] + row_2[-1] + row_3[-1] + row_4[-1] + row_5[-1])/5
print(average_rating)

4.2


## 7. Opening a File (OPTIONAL)

The data set we've been working with so far is a small snippet from a much larger data set from Kaggle. See data source: [Mobile App Store Data Set (Ramanathan Perumal)](https://www.kaggle.com/ramamet4/app-store-apple-data-set-10k-apps). 
The data set contains 7,197 rows and 16 columns, which amounts to 115,152 (7,197 * 16) data points. It would be impossible to type all the data points manually into our computer and have them saved in the computer memory. However, we can always download a file and open it in our computer by using the `open()` command. For example if we have a file saved on the computer called "AppleStore.csv", we could open it like this:

*my_file = open('AppleStore.csv')*

Once we've opened the file we can read it in using a command called `reader()`. We need to import the `reader()` command from the **csv module** using the code `from csv import reader` (a **module is a collection of commands and variables**). Then we can transform the file into a list of lists using the `list()` command. The entire process looks like this:

In [ ]:
my_file = open('AppleStore.csv', encoding='utf8')

from csv import reader
read_file = reader(my_file)
apps_data = list(read_file)

#To print out the first five rows of apps_data
print(apps_data[:5])

#To find out the length of our data set
len(apps_data)

FileNotFoundError: ignored

## 7.1. Dealing with files with the context manager - Lidando com arquivos com o gerenciador de contexto
We started to open CSV files. We did so using a very simplified snippet of code, which would not be the case in professional code. Normally we work with the context manager `with`.  
The Python `with` statement creates a runtime context that allows you to run a group of statements under the control of a context manager. In case of opening files, the `with` closes them automatically for us at the end of the block.

Each file should be closed once we finished the work -- that will release resources back to OS. It is not necessary in case of few files (such as in these training notebooks), but the best practices is to do so everytime. It will prevent many possible problems in your future career as Data Scientist. We can use two following ways:

In [ ]:
# context manager
with open('Florita_Costa.csv', encoding='utf8') as my_file: 
    from csv import reader
    read_file = reader(my_file)
    apps_data = list(read_file)

    #To print out the first five rows of apps_data
    print(apps_data[8])

    #To find out the length of our data set
    len(apps_data)

    
# or a more classical approach      
print("*** Second way to do it ***")
my_file_2 = open('Florita_Costa.csv', encoding='utf8')
read_file = reader(my_file_2)
apps_data = list(read_file)
print(apps_data[:5])
len(apps_data)

# closing resources
my_file_2.close() 

['3/29/1945', '6', 'Edição 04790', 'Diário do Flamengo', 'Aborda o jogador Jarbas, que atua pelo clube há treze anos, destacando-o como grande profissional. Cita a derrota po 1 x 0 para o Botafogo no jogo realizado no dia anterior;', '']
*** Second way to do it ***
[['Data', 'Página', 'Edição', 'Nome_Coluna', 'Descricoes_Citacoes', 'Citacoes '], ['3/18/1945', '8', 'Edição 04781', 'Diário do Flamengo ', 'Relato almoço com Flavio Costa', '"Ontem a família rubro-negra ofereceu a Flavio um almoço íntimo no Lido, em homenagem ao seu regresso vitorioso ao Flamengo. Idealizou a festa o Coronel Orsini Coriolano que, imediatamente, teve o apoio de seus amigos e companheiros de clube." "Flavio com aquele seu geitão acanhado, respondeu a todos, dizendo da sua emoção pela lembrança e que tudo o que tinha feito nada era seu e sim o resultado dos ensinamentos técnicos colhidos em sua trajetoria pelo Flamengo e os morais pela convivencia com tão bons amigos."'], ['3/20/1945', '6', 'Edição 04782', 'Di

In [ ]:
with open('Florita_Costa.csv', encoding='utf8') as my_file: 
    from csv import reader
    read_file = reader(my_file)
    apps_data = list(read_file)
for whatever in apps_data:
    app = whatever[-2]
    print(app)

#Extrair citações da planilha da Florita Costa

## 8. Repetitive Processes

In the previous task, we have retrieved ratings manually. However, try to retrieve 7,197 ratings manually is impractical because it takes a lot of time. How can we find a way that retrieve all 7,197 ratings in just a couple seconds? Luckily, Python offers us an easy way to repeat a process. Let's look at the following example:

In [ ]:
ratings = [3, 10, 2, 6, 8, 1]

for element in ratings:
    print(element)

3
10
2
6
8
1


Do you remember the first example we had above? Where we wanted to retrieve the last element for each list in `app_data_set`. We can translate this process using the for loop in Python, like this:

In [ ]:
app_data_set = [row_one, row_two, row_three, row_four, row_five]

for each_list in app_data_set:
    rating = each_list[-1]
    print(rating)

for whatever in app_data_set:
    app = whatever[0]
    print(app)

3.5
4.5
4.5
4.5
4.0
Facebook
Instagram
Clash of Clans
Temple Run
Pandora - Music & Radio


The code above  takes each list element from `app_data_set` and assigns it to ``each_list`` (which basically becomes a variable that stores a list). See in the example below how each element in the ``app_data_set`` is taken out (or isolated) and gets printed onto the screen:

In [ ]:
app_data_set = [row_one, row_two, row_three, row_four, row_five]

for each_list in app_data_set:
    print(each_list)

['Facebook', 0.0, 'USD', 2974676, 3.5]
['Instagram', 0.0, 'USD', 2161558, 4.5]
['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
['Temple Run', 0.0, 'USD', 1724546, 4.5]
['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]


To make it more understandable, it basically does the following:

In [ ]:
app_data_set = [row_one, row_two, row_three, row_four, row_five]

print(app_data_set[0])
print(app_data_set[1])
print(app_data_set[2])
print(app_data_set[3])
print(app_data_set[4])

['Facebook', 0.0, 'USD', 2974676, 3.5]
['Instagram', 0.0, 'USD', 2161558, 4.5]
['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
['Temple Run', 0.0, 'USD', 1724546, 4.5]
['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]


The for loop technique requires us to write only two lines of code regardless of the number of rows in the data set, even if the data set has couple millions rows! :)

One thing to pay attention to: do not forget to **indent** the code after the `for` line. To indent means to use for example TAB at the beginning of next line if your editor does not do it automatically for you.

### Task 1.3.8: 
Use the new technique we've learned to print all the rows in the `app_data_set` list of lists.

In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_4 = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_5 = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]

app_data_set = [row_1, row_2, row_3, row_4, row_5]

# Start your code below:
for each_row in app_data_set:
    print(each_row)


['Facebook', 0.0, 'USD', 2974676, 3.5]
['Instagram', 0.0, 'USD', 2161558, 4.5]
['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
['Temple Run', 0.0, 'USD', 1724546, 4.5]
['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]


## 9. For Loops

What we just learned above is called <b>for loop</b>, as we have already mentioned.

There are three structural parts in a <b>for loop</b>:
1. iteration variable
2. iterable variable
3. the body of the for loop

In [ ]:
a_list = [1, 2, 3]

for value in a_list:
    print(value)
    print(value - 1)

# value - is the iteration variable
# a_list - is the iterable variable
# print(value) & print(value - 1) - belong to the body of the loop

1
0
2
1
3
2


The indented code in the <b>body</b> gets executed the same number of times as elements in the <b>iterable variable</b>. If the iterable variable is a list that has three elements, the indented code in the body gets executed three times. We call each code execution an<b> iteration</b>, so there'll be three iterations for a list that has three elements. For each iteration, the <b>iteration variable</b> will take a different value, following this pattern:

- In the first iteration, the value is the first element of the iterable (we have the list `[1, 2, 3]` as the iterable, so the value will be 1).
- In the second iteration, the value is the second element of the iterable (we have the list `[1, 2, 3]` as the iterable, so the value will be 2).
- In the third iteration, the value is the third element of the iterable (we have the list `[1, 2, 3]` as the iterable, so the value will be 3).

Do you know that the code outside the loop body can also interact with the code inside the loop body? Look at the following example:

In [ ]:
a_list = [1, 2, 3, 4, 5, 6, 7]

a_sum = 0 # a variable outside the loop body

for value in a_list: # for every iteration of the loop
    ######################Everything below is inside the loop body###################
    
    a_sum = a_sum + value # perform an addition between the current value 
    # of the iteration variable and the current value stored in a_sum, 
    # and assign the result of the addition back to a_sum
    print(a_sum) # print the value of the a_sum variable
    
    ######################Everything above is inside the loop body###################
    

1
3
6
10
15
21
28


### Task 1.3.9:
Compute the average app rating for the apps stored in the `app_data_set` variable.

1. Initialize a variable named `rating_sum` with a value of zero outside the loop body.
2. Loop (iterate) over the `app_data_set` list of lists. For each of the five iterations of the loop (for each row in `app_data_set`):
3. Extract the rating of the app and store it to a variable named `rating`. The rating is the last element of each row.
4. Add the value stored in rating to the current value of the `rating_sum`.
5. Outside the loop body, divide the rating sum (stored in `rating_sum`) by the number of ratings to get an average value. Store the result in a variable named `avg_rating`.


In [ ]:
row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_4 = ['Temple Run', 0.0, 'USD', 1724546, 4.5]
row_5 = ['Pandora - Music & Radio', 0.0, 'USD', 1126879, 4.0]

app_data_set = [row_1, row_2, row_3, row_4, row_5]

# Start your code below:
rating_sum = 0
for each_list in app_data_set:
    rating = each_list[-1]
    rating_sum = rating_sum + rating
avg_rating = rating_sum/5
print(avg_rating)

4.2
